### ISSUE TITLE
[api-extractor] 3.7-style accessors lose their @internal marker in the api report

### ISSUE THREAD

**Issue by seritools** [microsoft/rushstack#1619]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

With TS 3.7 the .d.ts files now emit accessor declarations. However, api-extractor currently misses the `@internal` marker on those when generating the api report file. This also causes a `ae-incompatible-release-tags` warning when referencing another internal type in the accessor type.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

This is the exact pattern I use in my project:

```typescript
import { Observable, ReplaySubject } from 'rxjs';

/**
 * Marked as internal, so ae emits a warning if it is referenced in a non-internal api definition
 * @internal
 */
export class _Private {}

export class Test {
  private _stuff = new ReplaySubject<_Private>(1);

  /**
   * This one loses its internal marker in the api and thus emits a warning since it references
   * the internal _Private class
   * @internal
   */
  public get stuff(): Observable<_Private> {
      return this._stuff;
  }
}
```

**What is the expected behavior?**

The `@internal` marker should stay and no warning should be emitted.

(I think api-documenter is not updated yet for 3.7/accessor documentation, so losing those completely is currently correct, right?)

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** api-extractor
* **Tool Version:** 7.5.5
* **Node Version:** v12.13.0
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** Windows 10

**Comment by octogonz** [comment]
@seritools I see, so TypeScript 3.7 produces this output:

**lib/index.d.ts**
```
    . . .
    /**
     * This one loses its internal marker in the api and thus emits a warning since it references
     * the internal _Private class
     * @internal
     */
    get stuff(): Observable<_Private>;
    . . .
```

...whereas earlier TypeScript produces this output:
**lib/index.d.ts**
```
    . . .
    /**
     * This one loses its internal marker in the api and thus emits a warning since it references
     * the internal _Private class
     * @internal
     */
    readonly stuff: Observable<_Private>;
    . . .
```

And the API report seems to indicate that API Extractor isn't finding the TSDoc comment:

**repro.api.md**
```ts
// Warning: (ae-incompatible-release-tags) The symbol "Test" is marked as @public, but its signature references "_Private" which is marked as @internal
// 
// @public (undocumented)
export class Test {
    get stuff(): Observable<_Private>;
}
```

👍 Thanks for reporting this!

**Comment by seritools** [comment]
Yup, exactly.

Expected:
```typescript
// @public (undocumented)
export class Test {
    // @internal
    get stuff(): Observable<_Private>;
}
```

Actual: 
```typescript
// Warning: (ae-incompatible-release-tags) The symbol "Test" is marked as @public, but its signature references "_Private" which is marked as @internal
// 
// @public (undocumented)
export class Test {
    get stuff(): Observable<_Private>;
}
```

**Comment by seritools** [comment]
The accessors are completely missing in the docModel (`.api.json`) as well. This causes api-documenter to completely skip the documentation of all accessors.

**Comment by pmconne** [comment]
This continues to block my project's ability to upgrade to TypeScript 3.7.2. @octogonz, you labeled this "effort: easy" and "help wanted". I am completely unfamiliar with this code, but I'm willing to investigate if you (or someone) can point me in the right direction.

**Comment by octogonz** [comment]
Wasn't this fixed in 7.7.0 by PR https://github.com/microsoft/rushstack/pull/1646?

**Comment by pmconne** [comment]
I guess I will try it and find out. I assumed open issue meant not fixed.

**Comment by octogonz** [comment]
Please let us know! I don't remember why this issue didn't get closed. Maybe we just forgot because there was another similar issue.

**Comment by pmconne** [comment]
I can confirm 7.7.0 resolves this issue for me. AFAICT the issue should be closed. Thanks!

**Comment by octogonz** [comment]
Awesome, thanks @pmconne!
