### ISSUE TITLE
[rush] Incremental build reports InternalError for packages with optional peer dependencies

### ISSUE THREAD

**Issue by octogonz** [microsoft/rushstack#1621]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

In PR https://github.com/microsoft/rushstack/pull/1618 we introduced the ability to disable implicit preferred versions, by setting `implicitlyPreferredVersions=false`.  This eliminates certain installation errors, and it will default to being enabled for PNPM 4.x.

However, the Azure SDK reported an InternalError that occurs due to a bug in the improved incremental build logic that was recently introduced by PR https://github.com/microsoft/rushstack/pull/1526.

@mikeharder provided this repro:

```
git clone https://github.com/mikeharder/azure-sdk-for-js
git checkout f1a8795ea18fc5d4f2112838c82821f48b100695
rush update update --full
```

`rush link` fails with this callstack:

```
Error: Internal Error: Could not find peer dependency 'typescript' that satisfies version '*'

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
    at PnpmProjectDependencyManifest._addDependencyInternal (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmProjectDependencyManifest.js:117:31)
    at PnpmProjectDependencyManifest._addDependencyInternal (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmProjectDependencyManifest.js:74:22)
    at PnpmProjectDependencyManifest._addDependencyInternal (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmProjectDependencyManifest.js:74:22)
    at PnpmProjectDependencyManifest.addDependency (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmProjectDependencyManifest.js:33:14)
    at PnpmLinkManager._createLocalPackageForDependency (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmLinkManager.js:231:43)
    at PnpmLinkManager._linkProject (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmLinkManager.js:156:42)
    at promise.then (D:\git\rushstack\apps\rush-lib\lib\logic\pnpm\PnpmLinkManager.js:39:33)
```

Setting `"legacyIncrementalBuildDependencyDetection": true` in `experiments.json` eliminates the error.  But obviously that's not the solution we want.

## Details

The new incremental link logic is trying to crawl the dependencies of the `@rush-temp/abort-controller` project in order to collect the `shrinkwrap-deps.json` inventory.

It follows `@typescript-eslint/eslint-plugin`...
```yaml
  'file:projects/abort-controller.tgz':
    dependencies:
      '@typescript-eslint/eslint-plugin': 2.6.1_f826f0ccb5c1fa5c7ef10e2b959e7a19
```
...to `@typescript-eslint/experimental-utils`...
```yaml
  /@typescript-eslint/eslint-plugin/2.6.1_f826f0ccb5c1fa5c7ef10e2b959e7a19:
    dependencies:
      '@typescript-eslint/experimental-utils': 2.6.1_eslint@6.6.0+typescript@3.6.4
```
...to `@typescript-eslint/typescript-estree`...
```yaml
  /@typescript-eslint/experimental-utils/2.6.1_eslint@6.6.0+typescript@3.6.4:
    dependencies:
      '@typescript-eslint/typescript-estree': 2.6.1_typescript@3.6.4
```
...which looks like this:
```yaml
  /@typescript-eslint/typescript-estree/2.6.1_typescript@3.6.4:
    dependencies:
      debug: 4.1.1
      glob: 7.1.6
      is-glob: 4.0.1
      lodash.unescape: 4.0.1
      semver: 6.3.0
      tsutils: 3.17.1_typescript@3.6.4
    dev: false
    engines:
      node: ^8.10.0 || ^10.13.0 || >=11.10.1
    peerDependencies:
      typescript: '*'
    peerDependenciesMeta:
      typescript:
        optional: true
```

[This code](https://github.com/microsoft/rushstack/blob/927c1d99cc7bd15bc41c92bfd07fa62127027dd6/apps/rush-lib/src/logic/pnpm/PnpmProjectDependencyManifest.ts#L152) in PnpmProjectDependencyManifest.ts fails to find the `typescript: '*'` peer dependency.

**Comment by octogonz** [comment]
I noticed this entry:
```yaml
peerDependenciesMeta:
  typescript:
    optional: true
```

Looks like 25 days ago PR https://github.com/typescript-eslint/typescript-eslint/pull/990 converted TypeScript to be an "optional peer dependency".  This is a relatively new package manager feature that we need to check for.

**Comment by octogonz** [comment]
@iclanton @D4N14L FYI this is a somewhat important issue, since it's a regression for the improved incremental build feature.  The fix should be pretty easy.

**Comment by mikeharder** [comment]
I verified setting `"legacyIncrementalBuildDependencyDetection": true` in `experiments.json` eliminates the error in the Azure SDK repo.  However, we will likely wait until this issue is fixed to enable `implicitlyPreferredVersions=false`.

**Comment by octogonz** [comment]
I started work on PR https://github.com/microsoft/rushstack/pull/1624 which avoids reporting an error for a missing dependency when it is marked as an "optional peer dependency".

However, while that solved the first error, `rush link` still fails @mikeharder's repro with a later error where `typescript` is NOT an optional peer dependency.  The problem is with this logic:

https://github.com/microsoft/rushstack/blob/dffa822d4e248dd7b42b372d80b42de689b65387/apps/rush-lib/src/logic/pnpm/PnpmProjectDependencyManifest.ts#L192-L204

The "hoisting" we were relying on here was actually Rush's "implicit preferred dependencies" feature.  When we disable that, then `typescript` no longer appears at the root of the shrinkwrap file.

PNPM does "hoist" the `typescript` package, as you can see from this NodeJS trace:
```
D:\GitR\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\@typescript-eslint\experimental-utils\2.7.0_eslint@6.6.0+typescript@3.6.4>node
> for (x of require.resolve.paths('typescript')) { const y = path.join(x,'typescript/package.json'); console.log(fs.existsSync(y) + ': ' + y); }
false: D:\GitR\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\@typescript-eslint\experimental-utils\2.7.0_eslint@6.6.0+typescript@3.6.4\repl\node_modules\typescript\package.json
false: D:\GitR\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\@typescript-eslint\experimental-utils\2.7.0_eslint@6.6.0+typescript@3.6.4\node_modules\typescript\package.json
false: D:\GitR\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\@typescript-eslint\experimental-utils\node_modules\typescript\package.json
false: D:\GitR\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\@typescript-eslint\node_modules\typescript\package.json
false: D:\GitR\azure-sdk-for-js\common\temp\node_modules\.pnpm\registry.npmjs.org\node_modules\typescript\package.json
true: D:\GitR\azure-sdk-for-js\common\temp\node_modules\.pnpm\node_modules\typescript\package.json
. . .
```

...but (with `implicitPreferredVersions=false`) this PNPM hoisting is not explicitly reflected anywhere in the `pnpm-lock.yaml` file.

As it stands right now, our `shrinkwrap-deps.json` implementation is relying on an incorrect interpretation of the `pnpm-lock.yaml` file.  We need to get this fixed.

If someone can figure out how to determine which indirect dependencies get hoisted by PNPM, I'm willing to implement that logic and complete my PR.  @D4N14L @sachinjoseph

**Comment by octogonz** [comment]
I realized that we can probably solve this by parsing the `2.7.0_eslint@6.6.0+typescript@3.6.4` specifier and using that to resolve a missing peer dependency such as `typescript` to `3.6.4`.

I pushed a prototype of this idea to PR https://github.com/microsoft/rushstack/pull/1624.

@mikeharder Could you test this branch and confirm whether it solves your issue for `azure-sdk-for-js`?

It definitely caused `rush update` to complete successfully, however the build is failing because `common/temp/node_modules/.bin` no longer contains binaries for the (previously) implicitly preferred versions.  For example it can't find `tsc`.  It seems like Rush is doing the right thing here, because how is Rush supposed to know which binary to link.  So I'm interested to see how you would handle this.  Maybe you can create a project like `sdk/repo-tools/package.json` and use that to install your binaries?  Alternatively you could add `tsc` to `devDependencies` for every project that needs TypeScript.

**Comment by mikeharder** [comment]
@octogonz: Testing this change in our branch now.  So far, most of the errors were missing dependencies in our `package.json` files, so this change is finding bugs in our code that were previously hidden (which is a good thing).

**Comment by mikeharder** [comment]
@octogonz: After fixing our missing dev deps, we are still seeing two categories of build errors:

1. `rollup` cannot find some dependencies even though they are listed in `package.json`

2. `tsc` cannot find `@types/chai`, even though it is listed in both the top-level `package.json` and the `chai-exclude` `package.json`:

```
> tsc -p .

../../../common/temp/node_modules/.registry.npmjs.org/chai-exclude/2.0.2_chai@4.2.0/node_modules/chai-exclude/index.d.ts:1:23 - error TS2688: Cannot find type definition file for '@types/chai'.

1 /// <reference types="@types/chai" />
```

I am investigating these to determine if something is wrong in our repo or these are bugs in Rush/pnpm.

**Comment by mikeharder** [comment]
Repro steps (using build of Rush created from PR #1624)

```
git clone https://github.com/mikeharder/azure-sdk-for-js
git checkout 707d180adf2f45103129bbd33661d55c19e6b742
node ..\rushstack\apps\rush-lib\lib\start.js install
node ..\rushstack\apps\rush-lib\lib\start.js build
```

```
FAILURE (4)
================================
@azure/core-amqp (1 minute 42.4 seconds)
>>> @azure/core-amqp
tsc -p . && rollup -c 2>&1

dist-esm/src/index.js ? dist/index.js...
created dist/index.js in 609ms

dist-esm/src/index.js ? browser/index.js...
[!] (plugin Rollup Core) Error: Could not load events (imported by D:\Git\js-mh\common\temp\node_modules\.registry.npmjs.org\rhea-promise\1.0.0\node_modules\rhea-promise\dist\lib\container.js): ENOENT: no such file or directory, open 'D:\Git\js-mh\sdk\core\core-amqp\events'
Error: Could not load events (imported by D:\Git\js-mh\common\temp\node_modules\.registry.npmjs.org\rhea-promise\1.0.0\node_modules\rhea-promise\dist\lib\container.js): ENOENT: no such file or directory, open 'D:\Git\js-mh\sdk\core\core-amqp\events'

@azure/event-hubs (1 minute 42.4 seconds)
>>> @azure/event-hubs
tsc -p . && rollup -c 2>&1 && npm run extract-api

dist-esm/src/index.js ? dist/index.js...
(!) Circular dependency: dist-esm\src\eventHubClient.js -> dist-esm\src\connectionContext.js -> dist-esm\src\managementClient.js -> dist-esm\src\eventHubClient.js
(!) Circular dependency: dist-esm\src\eventHubClient.js -> dist-esm\src\sender.js -> dist-esm\src\eventHubSender.js -> dist-esm\src\eventHubClient.js
(!) Circular dependency: dist-esm\src\eventProcessor.js -> dist-esm\src\pumpManager.js -> dist-esm\src\eventProcessor.js
(!) Circular dependency: dist-esm\src\eventProcessor.js -> dist-esm\src\pumpManager.js -> dist-esm\src\partitionPump.js -> dist-esm\src\eventProcessor.jscreated dist/index.js in 1.1s

dist-esm/src/index.js ? browser/event-hubs.js...
[!] (plugin Rollup Core) Error: Could not load process (imported by D:\Git\js-mh\common\temp\node_modules\.registry.npmjs.org\debug\4.1.1\node_modules\debug\src\browser.js): ENOENT: no such file or directory, open 'D:\Git\js-mh\sdk\eventhub\event-hubs\process'
Error: Could not load process (imported by D:\Git\js-mh\common\temp\node_modules\.registry.npmjs.org\debug\4.1.1\node_modules\debug\src\browser.js): ENOENT: no such file or directory, open 'D:\Git\js-mh\sdk\eventhub\event-hubs\process'

@azure/eventhubs-checkpointstore-blob (3 minutes 1.1 seconds)
>>> @azure/eventhubs-checkpointstore-blob
tsc -p . && rollup -c 2>&1 && npm run extract-api

dist-esm/src/index.js ? dist/index.js...
created dist/index.js in 163ms

dist-esm/src/index.js ? browser/eventhubs-checkpointstore-blob.js...
[!] (plugin Rollup Core) Error: Could not load process (imported by D:\Git\js-mh\common\temp\node_modules\.registry.npmjs.org\debug\4.1.1\node_modules\debug\src\browser.js): ENOENT: no such file or directory, open 'D:\Git\js-mh\sdk\eventhub\eventhubs-checkpointstore-blob\process'
Error: Could not load process (imported by D:\Git\js-mh\common\temp\node_modules\.registry.npmjs.org\debug\4.1.1\node_modules\debug\src\browser.js): ENOENT: no such file or directory, open 'D:\Git\js-mh\sdk\eventhub\eventhubs-checkpointstore-blob\process'

@azure/service-bus (2 minutes 19.6 seconds)
>>> @azure/service-bus
tsc -p . && rollup -c 2>&1 && npm run extract-api
../../../common/temp/node_modules/.registry.npmjs.org/chai-exclude/2.0.2_chai@4.2.0/node_modules/chai-exclude/index.d.ts(1,23): error TS2688: Cannot find type definition file for '@types/chai'.
================================
```

**Comment by mikeharder** [comment]
It appears the above issues repro with `pnpm@3.8.1`, but they **do not** repro with `pnpm@4.2.2`.  We are hesitant to update to `pnpm@4` since it drops support for Node 8 (which we still need to support), but it may be the best/only option in this case.

**Comment by octogonz** [comment]
```
C:\GitR\azure-sdk-for-js>git checkout 707d180adf2f45103129bbd33661d55c19e6b742
fatal: reference is not a tree: 707d180adf2f45103129bbd33661d55c19e6b742
```
Is the hash correct?

**Comment by octogonz** [comment]
Oh I see, it's a private fork.

**Comment by mikeharder** [comment]
Correct, this is the commit:

https://github.com/mikeharder/azure-sdk-for-js/commit/707d180adf2f45103129bbd33661d55c19e6b742

Here's a later commit with `pnpm@4` which doesn't repro:

https://github.com/mikeharder/azure-sdk-for-js/commit/9c293f01532c7ebeccc5f84bcedab27163caf366

I'm working in this branch in my fork:

https://github.com/mikeharder/azure-sdk-for-js/commits/implicitly-preferred-versions-2

**Comment by mikeharder** [comment]
@octogonz: After further discussion we are fine with updating to `pnpm@4.2.2` when we set `implicitlyPreferredVersions=false`.  So we approve this PR.

We are not planning to investigate this difference between `pnpm@3.8.1` and `pnpm@4.2.2` further, but if you do decide to investigate we'd love to hear what you find.

**Comment by octogonz** [comment]
I started to look at it, but unfortunately I'm not very familiar with how Rollup works.  I was hoping to find some minimal entries that you could add to `preferredVersions` table to restore whatever was working from when `implicitlyPreferredVersions=true`, but I don't have time to pursue that.

**Comment by mikeharder** [comment]
If you were going to investigate anything here I would recommend the `tsc` error, but from our perspective if `pnpm@4` works that's good enough to move forward.

From all the investigation I've done so far, everything looks identical between `pnpm@3` and `pnpm@4`, but something must be slightly different (maybe nested deep in the `node_modules` folder).
