### ISSUE TITLE
[rush] install/update/link fails when using git versions for dependencies

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [microsoft/rushstack#1749]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**
A transitive dependency of a project in a rush repo uses a "github" version specifier for a dependency to pull that package from a fork, instead of from a tagged upstream release.

This _used_ to work, but after updating rush/pnpm, it now gives rush fits and while `rush update` can create a `pnpm-lock.yaml`, `rush link` cannot complete and `rush install` cannot process the generated `pnpm-lock.yaml` file.

`rush install` or `rush update` after the problem lockfile is written:
```
ERROR: Cannot parse PNPM shrinkwrap version specifier: "github.com/chfritz/node-xmlrpc/948db2fbd0260e5d56ed5ba58df0f5b6599bbe38" for "xmlrpc"
```
From a pristine checkout, deleting the lockfile and then running `rush update` produces:
```
ERROR: The value for ["xmlrpc@github.com/chfritz/node-xmlrpc/948db2fbd0260e5d56ed5ba58df0f5b6599bbe38"] is "undefined" and cannot be serialized as JSON
```

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

I've made a minimal rush project demonstrating the issue.  In this case I've put the problematic package reference as a direct dependency of the project in the rush repo, but this produces identical errors to the several-steps-removed case of a transitive dependency encountered in my real application:

https://github.com/mgabeler-lee-6rs/rush-busted/tree/cac3e5d34ccdac2586d7889df7f380939c2ef451

Clone the issue and try:
* `rm -f common/config/rush/pnpm-lock.yaml`
* `rush update`
* `rush install`
* `rush link`

**What is the expected behavior?**
Rush should support version specifiers that (p)npm support

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** `rush`
* **Tool Version:** `5.20.0` -- and many others.  I've tried a very large set of rush+pnpm versions and have found none that work
* **Node Version:** 10.19.0 (and others)
  * **Is this a LTS version?** yes
  * **Have you tested on a LTS version?** yes
* **OS:** Linux

**Comment by mgabeler-lee-6rs** [comment]
Side note: this _used_ to work on older versions of rush

**Comment by arri-cc** [comment]
I wanted to confirm if the problem I'm seeing is related to this issue.

I have a monorepo that includes an Expo based React Native application.  Because Expo relies on a fork of react-native, we have to take a dependency on a hosted tar.gz file instead of a package hosted in an npm registry.  Like the following:
https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz

While I can add this package via `pnpm` directly: `pnpm add https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz`, I'm unable to add this package via `rush`.  It also appears that `rush` does not support the `link:` style package url.

If I add the package via `pnpm` then run `rush update`  it tries to find the package using the url as a version number based on values in the shrinkwrap file, like this:

```text
react-native@https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz_react-native@0.61.4+react@16.9.0
```

**Comment by octogonz** [comment]
This fix was released with Rush 5.27.1

**Comment by arri-cc** [comment]
it's possible my problem is different, as it still persists.  I can open a new issue
