### ISSUE TITLE
[rush] strictPeerDependencies is not enforced for monorepo packages

### ISSUE THREAD

**Issue by dfee** [microsoft/rushstack#1865]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**
If you've got @mono/package-a that has a peerDependency on `foo`, you can install it into another project @mono/package-b (while `strictPeerDependencies=true` and you won't get an error. 

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

**What is the expected behavior?**

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** Rush
* **Tool Version:** 5.23.1
* **Node Version:** 12.16.3
  * **Is this a LTS version?** Yes 
  * **Have you tested on a LTS version?** ...
* **OS:** Ubuntu / MacOS

**Comment by dfee** [comment]
Here's an example: https://github.com/dfee/rush-issues/tree/peer-deps

You'll notice that `service-b` relies on `lib-b` which has a peer-dep on `luxon`. Rush doesn't seem to mind.

**Comment by iclanton** [comment]
Thanks for reporting this. Looks like this is an issue. @D4N14L - this will probably be fixed by the workspaces work that you're doing. Can you explicitly test this?

**Comment by D4N14L** [comment]
Closing out, this is resolved when using PNPM workspaces (see #1938)

**Comment by dietergeerts** [comment]
This is closed, though it still doesn't seem to work. The docs also doesn't tell more about how to actually get it working. My config:
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/rush/v5/rush.schema.json",
  "rushVersion": "5.26.0",
  "pnpmVersion": "5.2.6",
  "pnpmOptions": {
    "strictPeerDependencies": true
  },
  "nodeSupportedVersionRange": ">=12.0.0 <13.0.0",
  "ensureConsistentVersions": true,
```

**Comment by D4N14L** [comment]
> This is closed, though it still doesn't seem to work. The docs also doesn't tell more about how to actually get it working.

This is intentional. The feature is still experimental. However, if you would like to try it out, it can be enabled by setting:
```json
"pnpmOptions": {
   "useWorkspaces": true
}
```
